version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - backend
    healthcheck: # On verifie que le service est bien up
      test: ["CMD", "redis-cli", "ping"] 
      interval: 5s
      timeout: 5s
      retries: 3

  vote:
    image: yoannchh/3dokr-vote:latest
    ports:
      - "5001:5000"
    depends_on:
      - redis
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - frontend
      - backend
    healthcheck: # On fait une requete sur le service pour verifier qu'il est up
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 5s
      timeout: 5s
      retries: 3

  worker:
    image: yoannchh/3dokr-worker:latest
    depends_on:
      - redis
      - postgres
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - backend
    healthcheck: # On verifie que le process n'a pas crash.
      test: ["CMD-SHELL", "pidof dotnet || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3

  result:
    image: yoannchh/3dokr-result:latest
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - frontend
      - backend
    healthcheck: # On fait une requete sur le service pour verifier qu'il est up
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck: # On verifie que le service est bien up et ready pour read/write
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
    
volumes:
  postgres_data:

networks:
  frontend:
    driver: overlay  
  backend:
    driver: overlay  


